#!/usr/bin/env python

import os

Import('envGlobal')

env = envGlobal.Clone()

files = env.Glob('*.cpp')

env.Append(LIBS=['tasking', 'gtest', 'pthread'])

if env['PLATFORM'] == 'custom' and 'test' in COMMAND_LINE_TARGETS:
	print('Unit tests can not run without a platform specific implementation!')
	exit(-1)

if env['GTEST_SUPPORT_NEEDED'] == 'yes' and env['PLATFORM'] != 'none' and env['PLATFORM'] != 'linux' and env['PLATFORM'] != 'cpp11':
	print('gtest is not supported for platform "' + env['PLATFORM'] + '". To test Tasking API choose bare metal none, linux, or cpp11')
	exit(-1)

env.Append(LIBS=['rt'])

program = env.Program('tasking_test', files)

Return('program')
