#!/usr/bin/env python

import os

Import('envGlobal')

env = envGlobal.Clone()

files = env.Glob('*.cpp')

if envGlobal['PLATFORM'] == 'none':
	env.Append(CXXFLAGS=['-DIS_NONE_PLATFORM'])
env.Append(LIBS=['tasking', 'googletest', 'pthread', 'rt'])

if env['PLATFORM'] == 'custom' and 'test' in COMMAND_LINE_TARGETS:
	print('Unit tests can not run without a platform specific implementation!')
	exit(-1)

env.RemoveFromList('CCFLAGS_warning', ['-Wundef'])
if env['PLATFORM'] not in ['none', 'linux', 'cpp11']:
    print('gtest is not supported for platform "' + env['PLATFORM'] + '". To test Tasking API choose bare metal none, linux, or cpp11')
    exit(-1)

if 'FORMAT' in envGlobal:
    print( "Format test files.")
    os.system('clang-format -style=file -i *.cpp')

program = env.Program('tasking_test', files)

Return('program')
