#!/usr/bin/env python

print("Build custom platform")

import os

Import('envGlobal')

# Setting for compilation of tasking framework the path to find includes of custom platform specific code.
envGlobal.Append(CPPPATH=[os.path.abspath('.')])

# Clone global environment to build custom example.
env = envGlobal.Clone()
env.Append(CPPPATH=[os.path.abspath('../../include')])

# All cpp files build the custom platform specific implementation.
files = env.Glob('*.cpp')

# Compile custom platform from files and link with tasking framework, which did not contain platform specific code.
program = env.Program('tasking_custom_plattform', files, LIBS=['tasking'])

# Install the program.
installCustom = env.Install(envGlobal['BINPATH'], program)

# The program is the target of the scons file for target all.
envGlobal.Alias('custom', installCustom)

Return('program')
