#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('../include')])

env = envGlobal.Clone()

files = env.Glob('*.cpp')

library = env.StaticLibrary(target = 'tasking-channels', source = files)
envGlobal.Install(env['LIBINSTALLPATH'], library)
Return('library')
