#!/usr/bin/env python

import os

Import('envGlobal')

env = envGlobal.Clone()

files = env.Glob('*.cpp')

env.Append(LIBS=['tasking', 'gtest', 'tasking-channels'])

env.Append(LIBS=['tasking', 'gtest'])
env.Append(LIBS=['pthread'])
if env['PLATFORM'] == 'outpost':
    env.Append(LIBS=['outpost_smpc', 'outpost_rtos', 'outpost_time', 'outpost_utils'])
env.Append(LIBS=['rt'])

program = env.Program('tasking_channels_test', files)

Return('program')
